global:
  scrape_interval: 15s

scrape_configs:
  - job_name: "backend"
    metrics_path: /api/metrics
    static_configs:
      - targets: ["host.docker.internal:8000"]

  - job_name: postgres
    static_configs:
      - targets: ["postgres-exporter:9187"]

  - job_name: "node-exporter"
    static_configs:
      - targets: ["node-exporter:9100"]
