global:
  scrape_interval: 15s

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["prometheus:9090"]

  - job_name: "loki"
    static_configs:
      - targets: ["loki:3100"]

  - job_name: "backend"
    metrics_path: /api/metrics
    static_configs:
      - targets: ["backend:8000"]

  - job_name: postgres
    static_configs:
      - targets: ["postgres-exporter:9187"] # Replace IP with the hostname of the docker container if you're running the container in a separate network
