{
 "title": "PoE API",
 "time": { "from": "now-24h", "to": "now" },
 "panels": [
  {
   "title": "Response Codes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    { "expr": "rate(poe_response_total[30m])", "legendFormat": "{{status_code}}" }
   ]
  },
  {
   "title": "How much we are lagging behind ninja",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    { "expression": "($B-$A) / 5", "type": "math" }
   ]
  },
  {
   "title": "Stashes fetched",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "rate(stash_counter_filtered[30m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Requests against PoE API",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    { "expr": "rate(poe_request_total[30m])", "legendFormat": "{{endpoint}}" }
   ]
  },
  {
   "title": "Changes in ChangeId",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "rate(change_id[$__rate_interval])",
     "legendFormat": "Current ChangeId"
    },
    {
     "expr": "rate(ninja_change_id[$__rate_interval])",
     "legendFormat": "Ninja ChangeId"
    }
   ]
  },
  {
   "title": "Score calculation times",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(rate(score_aggregation_duration_s_sum[$__rate_interval]) )/sum(rate(score_aggregation_duration_s_count[$__rate_interval]) )",
     "legendFormat": "times"
    }
   ]
  }
 ]
}