services:
  db:
    image: postgres:17.2-alpine
    container_name: database
    restart: always
    env_file:
      - ../.env
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
